### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by KarenIMont** [SistemasTecTlaxiaco/actividad-4-mapa-mental-KarenIMont#2]
[Conjuntos_KarenIraisMontalvoReyes.pdf](https://github.com/user-attachments/files/17088475/Conjuntos_KarenIraisMontalvoReyes.pdf)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by Eddi3mendoz** [comment]
Manejo conceptual y dominio del tema: 5/5
Relación entre los conceptos incluidos en el mapa: 5/5
Calidad de la presentación: 5/5
Jerarquía: 5/5
CALIFICACIÓN: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
